# Default values for lp-tntcatlogapi microservice.

nodeSelector:
  kubernetes.io/os: linux

serviceAccount:
  create: true
  name: "lp-tntcatlogapi"
  automountServiceAccountToken: false

service:
  enabled: true
  port: 8080
  enableHttps: true
  env:
  - name: ConnectionStrings
    value: db-env-dev 

configmap:
  enabled: true
  configuration:
    LOGGING_LEVEL: 'Error'
    ASPNETCORE_TEMP: '/lpusr/lpapi/Logs'  
    TMPDIR: '/lpusr/lpapi/Logs'

deployment:
  containerPort: 8080
  configChecksum: true   
  securityContext:      
      runAsNonRoot: true
      fsGroup: 2000
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  serviceAccountName: lp-tntcatlogapi
  serviceAccount: lp-tntcatlogapi
  imagePullPolicy: Always
  hostNetwork: false
  hostPID: false
  hostIPC: false
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 600
  containers:
    securityContext:
      runAsUser: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsGroup: 3000
      capabilities:
        drop:
           - ALL   

# resources:
#   requests:
#     memory: "1000Mi"
#     cpu: "350m"
#   limits:
#     memory: "1200Mi"
#     cpu: "5000m"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 75

probes:
  enabled: true
  livenessProbe:
    httpGet:
      path: /liveness
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    httpGet:
      path: /readiness
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 5
  terminationMessagePath: /dev/termination-log
  terminationMessagePolicy: File

      
secretProviderClass:
  enabled: true
  name: lp-tntcatlogapi
  secretObjects:
    type: Opaque
    data:
      - key: db-env-dev
        objectName: db-env-dev
  keyVaultSecrets:
    - objectName: db-env-dev
      objectType: secret
      objectVersion: ''