{{- if .Values.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
  labels:
    {{- include "leasepoint.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  provider: {{ .Values.secretsCloudProvider }}
  secretObjects:
    - secretName: {{ .Release.Name }}-secret    # write the name to create in kubernetes secret for Env var
      type: {{ .Values.secretProviderClass.secretObjects.type }}
      {{- with .Values.secretProviderClass.secretObjects.data }}
      data:
    {{- toYaml . | nindent 6 }}
    {{- end }}
  parameters:
    useVMManagedIdentity: {{ .Values.secrets.useVMManagedIdentity | quote }}
    userAssignedIdentityID: {{ .Values.secrets.userAssignedIdentityID }}
    usePodIdentity: {{ .Values.secrets.usePodIdentity | quote }}
    keyvaultName: {{ .Values.azure.keyvaultName }}               # the name of the KeyVault
    objects: |
      array:
      {{- range $key, $val := .Values.secretProviderClass.keyVaultSecrets }}
        - |
          objectName: {{ $val.objectName }}
          objectType: {{ $val.objectType }}
          objectVersion: {{ $val.objectVersion | quote }}
      {{- end }}
    resourceGroup: {{ .Values.azure.resourceGroup }}          # [REQUIRED for version < 0.0.4] the resource group of the KeyVault
    subscriptionId: {{ .Values.azure.subscriptionId }}          # [REQUIRED for version < 0.0.4] the subscription ID of the KeyVault
    tenantId: {{ .Values.azure.tenantId }}
{{- end }}